import type { CSSProperties } from "react";

export const authStyles = {
  bg: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #f0f9e8 0%, #e8f7f0 50%, #e8f4fd 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "32px 16px",
    fontFamily: "'DM Sans', system-ui, sans-serif",
  } as CSSProperties,
  card: {
    background: "#fff",
    borderRadius: 20,
    padding: "40px 36px",
    width: "100%",
    maxWidth: 420,
    boxShadow: "0 4px 40px rgba(0,0,0,0.08)",
  } as CSSProperties,
  logoRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
    marginBottom: 28,
    textDecoration: "none",
  } as CSSProperties,
  logoBox: {
    width: 40,
    height: 40,
    borderRadius: 10,
    fontSize: 18,
    background: "linear-gradient(135deg, #86C540, #5DC2D1)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  } as CSSProperties,
  brand: {
    fontSize: 22,
    fontWeight: 700,
    fontFamily: "Georgia, serif",
    background: "linear-gradient(135deg, #86C540, #5DC2D1)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
  } as CSSProperties,
  heading: {
    fontSize: 22,
    fontWeight: 600,
    color: "#111827",
    textAlign: "center",
    marginBottom: 4,
  } as CSSProperties,
  sub: {
    fontSize: 13,
    color: "#9ca3af",
    textAlign: "center",
    marginBottom: 28,
  } as CSSProperties,
  link: {
    color: "#86C540",
    fontWeight: 500,
    textDecoration: "none",
  } as CSSProperties,
  label: {
    fontSize: 12,
    fontWeight: 600,
    color: "#374151",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    marginBottom: 6,
  } as CSSProperties,
  input: {
    width: "100%",
    border: "1.5px solid #e5e7eb",
    borderRadius: 10,
    padding: "12px 14px",
    fontSize: 14,
    color: "#111827",
    outline: "none",
    background: "#fafafa",
    fontFamily: "inherit",
    boxSizing: "border-box",
  } as CSSProperties,
  btn: {
    width: "100%",
    padding: 13,
    border: "none",
    borderRadius: 10,
    background: "linear-gradient(135deg, #86C540, #5DC2D1)",
    color: "#fff",
    fontSize: 15,
    fontWeight: 600,
    cursor: "pointer",
    marginTop: 8,
    fontFamily: "inherit",
  } as CSSProperties,
  error: {
    padding: "10px 14px",
    background: "#fef2f2",
    border: "1px solid #fecaca",
    borderLeft: "4px solid #ef4444",
    borderRadius: 8,
    fontSize: 13,
    color: "#dc2626",
    marginBottom: 16,
  } as CSSProperties,
};